export const DoruzuTrait = {
    // Gender
    DIVINE: 'Divine',

    // Chakra
    AIR: 'Air',
    ROOT: 'Root',
    CROWN: 'Crown',
    WATER: 'Water',
    ICE: 'Ice',
    SACRAL: 'Sacral',
    LIGHTNING: 'Lightning',
    SOLAR_PLEXUS: 'Solar Plexus',
    LIGHT_AURA: 'Light Aura',
    THIRD_EYE: 'Third Eye',
    THROAT: 'Throat',
    FIRE: 'Fire',

    // Background
    NIGHT_MOON: 'Night Moon',
    MOON_WOLF: 'Moon Wolf',
    SIGMA: 'Sigma',
    DUNGEON: 'Dungeon',
    ISLAND: 'Island',
    SHRINE: 'Shrine',
    ABSTRACT: 'Abstract',
    CLOUD_BIG_SUN: 'Cloud Big Sun',
    NIGHT_MOON_CLOUD: 'Night Moon Cloud',
    PINK_MOON: 'Pink Moon',
    NIGHT_MOON_CLOUD_STARS: 'Night Moon Cloud Stars',
    THUNDER: 'Thunder',
    CITY_LIGHT: 'City Light',
    BATTLE: 'Battle',
    SPIRIT_COMPANIONS: 'Spirit Companions',

    // Weapons
    DRAGON_SWORD: 'Dragon Sword',
    LIGHT_SABER: 'Light Saber',
    HOLY_SWORD: 'Holy Sword',
    ELEMENTAL_SWORD: 'Elemental Sword',
    DOUBLE_EDGED_SWORD: 'Double Edged Sword',
    DUAL_AXES: 'Dual Axes',
    ENERGY_BLADES: 'Energy Blades',
    DUAL_SWORDS: 'Dual Swords',
    CYBORG_ARMS: 'Cyborg Arms',
    GAUNTLETS: 'Gauntlets',
    PLASMA_GUN: 'Plasma Gun',
    WINCHESTER_SHOTGUN: 'Winchester Shotgun',
    HAND_GUN: 'Hand Gun',
    GUNBLADE: 'Gunblade',
    CROSSBOW: 'Crossbow',
    BOW_AND_ARROW: 'Bow And Arrow',
    MAGICAL_WAND: 'Magical Wand',
    ENERGY_WHIP: 'Energy Whip',
    SPELL_CARDS: 'Spell Cards',
    RING_OF_DESTINY: 'Ring of Destiny',
    ELEMENTAL_ORBS: 'Elemental Orbs',
    MAGIC_STAFF: 'Magic Staff',
    BO_STAFF: 'Bo Staff',
    SHURIKEN: 'Shuriken',
    NUNCHUCKS: 'Nunchucks',
    KUNAI: 'Kunai',
    FAN_BLADES: 'Fan Blades',
    KATANA: 'Katana',

    // Face
    DEATH_MASK: 'Death Mask',
    STEALTH_MASK: 'Stealth Mask',
    BARREL_SUNGLASSES: 'Barrel Sunglasses',
    BLUE_SHADES: 'Blue Shades',
    DARK_SHADES: 'Dark Shades',
    ORANGE_SHADES: 'Orange Shades',
    EYE_PATCH: 'Eye Patch',
    BEARD: 'Beard',
    BUSHY_GOATEE: 'Bushy Goatee',
    MUSTACHE: 'Mustache',
    GOATEE: 'Goatee',
    FACE_LIGHTNING: 'Lightning',
    FACE_EARTH: 'Earth',
    FACE_WATER: 'Water',
    FACE_FIRE: 'Fire',
    FACE_GLOWING: 'Glowing',
    CHAKRA_EYES: 'Chakra Eyes',
    GRADIENT: 'Gradient',
    CAT_EYES: 'Cat Eyes',
    DEMON_EYES: 'Demon Eyes',
    MULTICOLOR: 'Multicolor',
    SILVER: 'Silver',
    GOLD: 'Gold',
    CIGAR: 'Cigar',

    // Clothes
    WINGED_ROYAL_WHITE_DRESS: 'Winged Royal White Dress',
    WINGED_WARRIOR_PRINCESS: 'Winged Warrior Princess',
    WINGED_ROYAL_DRESS: 'Winged Royal Dress',
    WINGED_BATTLE_DRESS: 'Winged Battle Dress',
    GOTHIC_LOLITA: 'Gothic Lolita',
    STEAMPUNK_CORSET: 'Steampunk Corset',
    MAIDEN_GOWN: 'Maiden Gown',
    LOW_CUT_DRESS: 'Low Cut Dress',
    ROYAL_WHITE_DRESS: 'Royal White Dress',
    ROYAL_DRESS: 'Royal Dress',
    KINGSGUARD_ARMOR: 'Kingsguard Armor',
    BATTLE_DRESS: 'Battle Dress',
    HEROINE_ARMOR: 'Heroine Armor',
    DIVINE_ARMOR: 'Divine Armor',
    BLUE_CASUAL_TOP: 'Blue Casual Top',
    CASUAL_OUTFIT_MALE: 'Casual Outfit Male',
    RED_CASUAL_SHIRT: 'Red Casual Shirt',
    CASUAL_BLACK_HOODIE: 'Casual Black Hoodie',
    URBAN_PUNKESS: 'Urban Punkess',
    FUTURISTIC_ARMOR: 'Futuristic Armor',
    DEMONSLAYER: 'Demonslayer',
    SHRINE_MAIDEN: 'Shrine Maiden',
    LEGENDARY_KIMONO: 'Legendary Kimono',
    MONK: 'Monk',
    KIMONO: 'Kimono',
    FESTIVAL_KIMONO: 'Festival Kimono',
    ROBES_OF_WISDOM: 'Robes of Wisdom',
    ICE_SUIT: 'Ice Suit',
    PURPLE_CAPE: 'Purple Cape',
    ELEMENTAL_ROBES: 'Elemental Robes',
    CELESTIAL_ROBE: 'Celestial Robe',
    WITCH_ROBE: 'Witch Robe',
    OBSIDIAN_ARMOR: 'Obsidian Armor',
    DEMON_LORD: 'Demon Lord',
    DRAGON_SCALE_ARMOR: 'Dragon Scale Armor',
    TACTICAL: 'Tactical',
    SCI_FI_JUMPSUIT: 'Sci Fi Jumpsuit',
    SPACE_SUIT: 'Space Suit',
    MECHA_PILOT: 'Mecha Pilot',
    TACTICAL_VEST: 'Tactical Vest',
    MECHANIC_JUMPSUIT: 'Mechanic Jumpsuit',
    ASSASSIN: 'Assassin',
    STEALTH_ARMOR: 'Stealth Armor',
    NINJA_OUTFIT: 'Ninja Outfit',
    PIRATE_FEMALE: 'Pirate Female',
    PIRATE_MALE: 'Pirate Male',
    SUIT: 'Suit',
    SCHOOL_UNIFORM_GIRL: 'School Uniform Girl',
    SCHOOL_UNIFORM_BOY: 'School Uniform Boy',
    MAGIC_SCHOOL_OUTFIT: 'Magic School Outfit',
    BANDIT_COAT: 'Bandit Coat',
    TRENCH_COAT: 'Trench Coat',
    CYBERPUNK_JACKET: 'Cyberpunk Jacket',
    RED_CASUAL_JACKET: 'Red Casual Jacket',
    BLACK_SPORT_HOODIE: 'Black Sport Hoodie',
    BLUE_SPORT_HOODIE: 'Blue Sport Hoodie'
} as const

export type DoruzuTraitType = typeof DoruzuTrait[keyof typeof DoruzuTrait] 